# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: build
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    env:
      UV_LINK_MODE: copy

    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v5

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uvx ruff check --select=E9,F63,F7,F82
          # exit-zero treats all errors as warnings.
          uvx ruff check --exit-zero

      - name: Self Test
        id: yaclog-ksp
        uses: ./
        with:
          mod-name: Dummy
          output-path: /tmp/version.cfg

      - name: Print self-test result
        run:
          cat '${{ steps.yaclog-ksp.outputs.output-path }}'


  publish:
    name: Build and Publish
    needs:
      - test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get Changelog Information
        id: yaclog-show
        uses: https://git.offworldcolonies.nexus/drewcassidy/yaclog@1.6.2

      - name: Build
        run: uv build

      - uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: python-distribution.zip
          path: dist/
          compression-level: 0 # already compressed

      - name: Log in to Tea
        if: forge.event_name == 'push'
        run: >-
          tea login add 
          --url ${{ forge.server_url }} 
          --token ${{ secrets.FORGEJO_DEPLOY_TOKEN }}

      - name: Create release
        if: forge.event_name == 'push' && startsWith(forge.ref, 'refs/tags')
        run: >
          tea release create 
          --repo "${{ forge.repository }}"
          --title "${{ steps.yaclog-show.outputs.name }}"
          --note-file "${{ steps.yaclog-show.outputs.body-file }}"
          "${{ forge.ref_name }}"

      - name: Upload artifacts to release
        if: forge.event_name == 'push' && startsWith(forge.ref, 'refs/tags')
        run: >
          tea release assets create 
          --repo "${{ forge.repository }}"
          "${{ forge.ref_name }}" dist/*

      - name: Upload to PyPI
        run: uv publish ${{ !(forge.event_name == 'push' && startsWith(forge.ref, 'refs/tags')) && '--dry-run' || ''}}
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - name: Upload to Forgejo
        run: uv publish ${{ !(forge.event_name == 'push' && startsWith(forge.ref, 'refs/tags')) && '--dry-run' || ''}}
        env:
          UV_PUBLISH_USERNAME: ${{ forge.repository_owner }}
          UV_PUBLISH_PASSWORD: ${{ secrets.FORGEJO_TOKEN }}
          UV_PUBLISH_URL: ${{ forge.server_url }}/api/packages/${{ forge.repository_owner }}/pypi
          UV_PUBLISH_CHECK_URL: ${{ forge.server_url }}/api/packages/${{ forge.repository_owner }}/pypi